### PR TITLE
change curl to wp_remote_post

### PR DESCRIPTION
**Pull request by spirit1431007**
SM.MS图床上传测试未通过：`Invalid file source`

### CODE REVIEW

**Comment by mashirozx** [comment]
maybe this helps: <http://codechutney.com/posting-file-using-wp_remote_post/>

about binary file in form-data: <https://www.jianshu.com/p/29e38bcc8a1d>

**Comment by spirit1431007** [comment]
done

**Comment by mashirozx** [comment]
可以顺便把header.php的curl提醒也删了

**Comment by spirit1431007** [comment]
ok了

**Pull request merged**
